# title of the experiment
title: ian_single_segmentation
# Where to output everything, in this path a folder with
# the same name as the title is created containing checkpoints,
# logs and a copy of the config used
project_dir: ./results
seed: 33

# which experiment to execute: Segmentation or Generation
experiment:
  name: IANSegmentation

data_loader:
  dataset: ./datasets/Pulpy3D
  # which augmentations to use, see: augmentations.yaml
  augmentations: ./configs/augmentation.yml
  preprocessing: ./configs/preprocessing.yaml
  batch_size: 4
  max_length: 300
  samples_per_volume: 10
  num_classes: 1
  num_workers: 8
  # shape of a single patch
  patch_shape:
  - 80
  - 80
  - 80
  # reshape of the whole volume before extracting the patches
  resize_shape:
  - 360
  - 280
  - 160
  # uniform / label
  sampler_type: label
  accumlation_iter: 16

# which network to use
model:
  name: AttentionPosPadUNet3D

loss:
  name: Jaccard

lr_scheduler:
  name: Plateau
  patience: 25

optimizer:
  learning_rate: 0.1
  name: SGD

trainer:
  # Reload the last checkpoints?
  reload: False
  checkpoint: ./checkpoints/last.pth
  # train the network
  do_train: True
  # do a single test of the network with the loaded checkpoints
  do_test: False
  do_predict: False
  epochs: 300